// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ResidentController from "./resident_controller"
import MaskController from "./mask_controller"

application.register("hello", HelloController)
application.register("resident", ResidentController)
application.register("mask", MaskController)
