// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HiddenfieldController from "./hiddenfield_controller"
application.register("hiddenfield", HiddenfieldController)

import MaskController from "./mask_controller"
application.register("mask", MaskController)

import ResidentController from "./resident_controller"
application.register("resident", ResidentController)

import UnitsController from "./units_controller"
application.register("units", UnitsController)
